# Generated by Django 3.2.10 on 2022-05-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Health', 'Health'), ('Technology', 'Technology'), ('Games', 'Games'), ('Meetups', 'Meetups'), ('Music', 'Music'), ('Art', 'Art'), ('Food', 'Food'), ('Business', 'Business'), ('Sports', 'Sports')], max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], max_length=20)),
            ],
        ),
    ]
