# Generated by Django 3.2.10 on 2022-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
